name: Auto PR with GitHub CLI

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!master'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request with gh cli
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if PR already exists for this branch
          pr_exists=$(gh pr list --head "$GITHUB_REF_NAME" --json number --jq 'length')
          if [ "$pr_exists" -eq 0 ]; then
            gh pr create \
              --title "Auto PR from $GITHUB_REF_NAME" \
              --body "This pull request was automatically created by workflow." \
              --base main \
              --head "$GITHUB_REF_NAME" \
              --reviewer mahmudka
          else
            echo "PR already exists for this branch."
          fi
